FROM php:5.6-apache

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y libcurl4-gnutls-dev libpng-dev unzip cron re2c php5-imap python git

RUN docker-php-ext-install mysql curl gd zip mbstring mysqli
RUN a2enmod headers expires deflate rewrite

COPY config/php.ini /usr/local/etc/php/

COPY init.sh /usr/local/bin/init.sh

RUN chmod u+x /usr/local/bin/init.sh

ENV WEB_ROOT /var/www/html/
