# ------------------------------------------------------------------------
#
# Copyright 2005-2015 WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
#
# ------------------------------------------------------------------------

FROM wso2-appcloud/php:1.0.0-base

ENV WEB_ROOT /var/www/html/
ENV MNT /mnt

RUN git clone GIT_REPO_URL --branch GIT_REPO_BRANCH --single-branch "$MNT/"
RUN mv "$MNT"PROJECT_ROOT* "$WEB_ROOT/"
RUN rm -rf "$MNT"/*