FROM tomcat:8.0

ENV APP_WAR ARTIFACT_NAME
ENV WEB_APP_HOME /usr/local/tomcat/webapps/

RUN sed -i "s/unpackWARs=\"true\"/unpackWARs=\"false\"/g" /usr/local/tomcat/conf/server.xml \
        && sed -i "/\/Host/i  \\\t<Context path=\"/\" docBase=\"$APP_WAR\" debug=\"0\" reloadable=\"true\"></Context>" /usr/local/tomcat/conf/server.xml

COPY "$APP_WAR" "$WEB_APP_HOME/"

CMD ["catalina.sh", "run"]
