FROM php:5.6-apache

ENV PHP_APP_ZIP ARTIFACT_NAME
ENV UPLOAD_PATH /tmp/src
ENV WEB_ROOT /var/www/html/

RUN apt-get update && apt-get install -y unzip
RUN mkdir -p "$UPLOAD_PATH"
COPY "$PHP_APP_ZIP" "$UPLOAD_PATH/"
RUN unzip "$UPLOAD_PATH/$PHP_APP_ZIP" -d "$WEB_ROOT/"
RUN rm -rf "$UPLOAD_PATH/$PHP_APP_ZIP"
