FROM wso2-appcloud/php:1.0.0-base 

ENV PHP_APP_ZIP ARTIFACT_NAME
ENV UPLOAD_PATH /tmp/src
ENV WEB_ROOT /var/www/html/

RUN mkdir -p "$UPLOAD_PATH"
COPY "$PHP_APP_ZIP" "$UPLOAD_PATH/"
RUN unzip "$UPLOAD_PATH/$PHP_APP_ZIP" -d "$WEB_ROOT/"
RUN chmod -R 777 "$WEB_ROOT/"

ENTRYPOINT ["/usr/local/bin/init.sh"]

