# ------------------------------------------------------------------------
#
# Copyright 2005-2015 WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
#
# ------------------------------------------------------------------------

FROM wso2-appcloud/php:1.0.0-base

ENV PHP_APP_ZIP ARTIFACT_NAME
ENV UPLOAD_PATH /tmp/src
ENV WEB_ROOT /var/www/html/

RUN mkdir -p "$UPLOAD_PATH"
COPY "$PHP_APP_ZIP" "$UPLOAD_PATH/"
RUN unzip "$UPLOAD_PATH/$PHP_APP_ZIP" -d "$WEB_ROOT/" \
           && chmod -R 777 "$WEB_ROOT/"

ENTRYPOINT ["/usr/local/bin/init.sh"]

